name: yumemi_code_assignment
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  app_settings: ^5.1.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3+1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  jovial_svg: ^1.1.22
  json_annotation: ^4.9.0
  markdown: ^7.2.2
  riverpod_annotation: ^2.3.5
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/translations/
